// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260713035652_InitialSqlServer")]
    partial class InitialSqlServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Entities.AddOnService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChargeMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.ToTable("Add_on_Service", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChargeMethod = "Fixed",
                            IsAvailable = true,
                            ServiceName = "Trà đá & Cà phê",
                            UnitPrice = 20000m
                        },
                        new
                        {
                            Id = 2,
                            ChargeMethod = "By_Hour",
                            IsAvailable = true,
                            ServiceName = "Projector",
                            UnitPrice = 50000m
                        });
                });

            modelBuilder.Entity("backend.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CustomSetupNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("LayoutId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentDeadline")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SnapshotBasePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("SnapshotPriceModifier")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("LayoutId");

                    b.HasIndex("UserId");

                    b.ToTable("Booking", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetId = 1,
                            BookingStatus = "Awaiting_Payment",
                            CreatedAt = new DateTime(2026, 7, 13, 3, 56, 51, 765, DateTimeKind.Utc).AddTicks(3503),
                            EndTime = new DateTime(2026, 7, 14, 5, 56, 51, 765, DateTimeKind.Utc).AddTicks(2811),
                            LayoutId = 1,
                            PaymentDeadline = new DateTime(2026, 7, 13, 4, 6, 51, 765, DateTimeKind.Utc).AddTicks(3305),
                            SnapshotBasePrice = 50000m,
                            SnapshotPriceModifier = 0m,
                            StartTime = new DateTime(2026, 7, 14, 3, 56, 51, 765, DateTimeKind.Utc).AddTicks(2615),
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            AssetId = 2,
                            BookingStatus = "Confirmed",
                            CreatedAt = new DateTime(2026, 7, 13, 3, 56, 51, 765, DateTimeKind.Utc).AddTicks(3628),
                            EndTime = new DateTime(2026, 7, 15, 7, 56, 51, 765, DateTimeKind.Utc).AddTicks(3626),
                            LayoutId = 1,
                            SnapshotBasePrice = 1200000m,
                            SnapshotPriceModifier = 50000m,
                            StartTime = new DateTime(2026, 7, 15, 3, 56, 51, 765, DateTimeKind.Utc).AddTicks(3626),
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            AssetId = 2,
                            BookingStatus = "Checked_In",
                            CreatedAt = new DateTime(2026, 7, 13, 3, 56, 51, 765, DateTimeKind.Utc).AddTicks(3631),
                            EndTime = new DateTime(2026, 7, 13, 5, 56, 51, 765, DateTimeKind.Utc).AddTicks(3630),
                            LayoutId = 2,
                            SnapshotBasePrice = 900000m,
                            SnapshotPriceModifier = 0m,
                            StartTime = new DateTime(2026, 7, 13, 2, 56, 51, 765, DateTimeKind.Utc).AddTicks(3630),
                            UserId = 3
                        });
                });

            modelBuilder.Entity("backend.Entities.BookingServiceDetail", b =>
                {
                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsIncurred")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Unpaid");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal>("SnapshotUnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("BookingId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Booking_Service_Detail", (string)null);
                });

            modelBuilder.Entity("backend.Entities.InternalTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("RequiredStaffCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("TaskCategory")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TaskDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasDefaultValue("Unassigned");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Internal_Tasks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingId = 2,
                            CreatedAt = new DateTime(2026, 7, 13, 3, 56, 51, 765, DateTimeKind.Utc).AddTicks(4794),
                            RequiredStaffCount = 1,
                            TaskCategory = "LOGISTICS",
                            TaskDescription = "Setup Chữ U cho Booking #2 (Bob)",
                            TaskStatus = "Unassigned"
                        },
                        new
                        {
                            Id = 2,
                            BookingId = 3,
                            CreatedAt = new DateTime(2026, 7, 13, 3, 56, 51, 765, DateTimeKind.Utc).AddTicks(4903),
                            RequiredStaffCount = 1,
                            TaskCategory = "CLEANING",
                            TaskDescription = "Dọn phòng sau khi Booking #3 (Alice) checkout",
                            TaskStatus = "Unassigned"
                        });
                });

            modelBuilder.Entity("backend.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("FinalDue")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("InvoiceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("PaidUpfront")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Unpaid");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Invoice", (string)null);
                });

            modelBuilder.Entity("backend.Entities.RoomLayout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<string>("LayoutName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceModifier")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("SetupDurationMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("Room_Layout", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetId = 2,
                            LayoutName = "Chữ U",
                            MaxCapacity = 8,
                            PriceModifier = 50000m,
                            SetupDurationMinutes = 15
                        },
                        new
                        {
                            Id = 2,
                            AssetId = 2,
                            LayoutName = "Lớp học",
                            MaxCapacity = 10,
                            PriceModifier = 0m,
                            SetupDurationMinutes = 20
                        });
                });

            modelBuilder.Entity("backend.Entities.SpaceAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AreaM2")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensions")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Space_Asset", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaM2 = 0.96m,
                            AssetName = "Hot Desk 101",
                            AssetType = "Hot_Desk",
                            BasePrice = 50000m,
                            Capacity = 1,
                            Dimensions = "1.2m x 0.8m",
                            IsActive = true,
                            LocationName = "Lầu 1"
                        },
                        new
                        {
                            Id = 2,
                            AreaM2 = 20.00m,
                            AssetName = "Meeting Room A",
                            AssetType = "Meeting_Room",
                            BasePrice = 300000m,
                            Capacity = 10,
                            Dimensions = "5m x 4m",
                            IsActive = true,
                            LocationName = "Lầu 2"
                        });
                });

            modelBuilder.Entity("backend.Entities.TaskAllocation", b =>
                {
                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("TaskId", "StaffId");

                    b.HasIndex("StaffId");

                    b.ToTable("Task_Allocations", (string)null);
                });

            modelBuilder.Entity("backend.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@example.com",
                            FullName = "System Admin",
                            PasswordHash = "$2a$11$oXJahW8iQJCHJtDpVwVBoOyBpBO9Shrc/SQxDQvnXvRPhhuYJ7AeO",
                            Role = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "staff@example.com",
                            FullName = "John Staff",
                            PasswordHash = "$2a$11$oXJahW8iQJCHJtDpVwVBoOyBpBO9Shrc/SQxDQvnXvRPhhuYJ7AeO",
                            Role = "STAFF"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice@example.com",
                            FullName = "Alice User",
                            PasswordHash = "$2a$11$oXJahW8iQJCHJtDpVwVBoOyBpBO9Shrc/SQxDQvnXvRPhhuYJ7AeO",
                            Role = "USER"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob@example.com",
                            FullName = "Bob User",
                            PasswordHash = "$2a$11$oXJahW8iQJCHJtDpVwVBoOyBpBO9Shrc/SQxDQvnXvRPhhuYJ7AeO",
                            Role = "USER"
                        });
                });

            modelBuilder.Entity("backend.Entities.Booking", b =>
                {
                    b.HasOne("backend.Entities.SpaceAsset", "SpaceAsset")
                        .WithMany("Bookings")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Entities.RoomLayout", "RoomLayout")
                        .WithMany("Bookings")
                        .HasForeignKey("LayoutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RoomLayout");

                    b.Navigation("SpaceAsset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Entities.BookingServiceDetail", b =>
                {
                    b.HasOne("backend.Entities.Booking", "Booking")
                        .WithMany("BookingServiceDetails")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.AddOnService", "AddOnService")
                        .WithMany("BookingServiceDetails")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AddOnService");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("backend.Entities.InternalTask", b =>
                {
                    b.HasOne("backend.Entities.Booking", "Booking")
                        .WithMany("InternalTasks")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("backend.Entities.Invoice", b =>
                {
                    b.HasOne("backend.Entities.Booking", "Booking")
                        .WithMany("Invoices")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("backend.Entities.RoomLayout", b =>
                {
                    b.HasOne("backend.Entities.SpaceAsset", "SpaceAsset")
                        .WithMany("RoomLayouts")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SpaceAsset");
                });

            modelBuilder.Entity("backend.Entities.TaskAllocation", b =>
                {
                    b.HasOne("backend.Entities.User", "Staff")
                        .WithMany("TaskAllocations")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Entities.InternalTask", "InternalTask")
                        .WithMany("TaskAllocations")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InternalTask");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("backend.Entities.AddOnService", b =>
                {
                    b.Navigation("BookingServiceDetails");
                });

            modelBuilder.Entity("backend.Entities.Booking", b =>
                {
                    b.Navigation("BookingServiceDetails");

                    b.Navigation("InternalTasks");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("backend.Entities.InternalTask", b =>
                {
                    b.Navigation("TaskAllocations");
                });

            modelBuilder.Entity("backend.Entities.RoomLayout", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("backend.Entities.SpaceAsset", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("RoomLayouts");
                });

            modelBuilder.Entity("backend.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("TaskAllocations");
                });
#pragma warning restore 612, 618
        }
    }
}
